"""empty message

Revision ID: 02bf72a286cc
Revises: df7e10a2b3ba
Create Date: 2022-06-06 06:32:45.035943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bf72a286cc'
down_revision = 'df7e10a2b3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debit_proses', sa.Column('bulan', sa.String(length=10), nullable=False))
    op.add_column('ph_domestik', sa.Column('bulan', sa.String(length=10), nullable=False))
    op.add_column('ph_proses', sa.Column('bulan', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ph_proses', 'bulan')
    op.drop_column('ph_domestik', 'bulan')
    op.drop_column('debit_proses', 'bulan')
    # ### end Alembic commands ###
