"""empty message

Revision ID: 202bff3e4c99
Revises: b5e13d7fa08a
Create Date: 2022-05-29 11:36:56.093578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202bff3e4c99'
down_revision = 'b5e13d7fa08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l_b3',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jenis_limbah', sa.String(length=250), nullable=False),
    sa.Column('konstanta', sa.Integer(), nullable=False),
    sa.Column('satuan_awal', sa.String(length=60), nullable=False),
    sa.Column('nilai', sa.Integer(), nullable=False),
    sa.Column('konversi', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('l_b3')
    # ### end Alembic commands ###
