"""empty message

Revision ID: 4eacaa25be00
Revises: 2261d08c5166
Create Date: 2022-06-07 20:11:23.085757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eacaa25be00'
down_revision = '2261d08c5166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('l_b3', sa.Column('nilai_satuan', sa.Float(), nullable=False))
    op.add_column('l_b3', sa.Column('satuan', sa.String(length=60), nullable=False))
    op.drop_column('l_b3', 'satuan_awal')
    op.drop_column('l_b3', 'konstanta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('l_b3', sa.Column('konstanta', mysql.FLOAT(), nullable=False))
    op.add_column('l_b3', sa.Column('satuan_awal', mysql.VARCHAR(length=60), nullable=False))
    op.drop_column('l_b3', 'satuan')
    op.drop_column('l_b3', 'nilai_satuan')
    # ### end Alembic commands ###
