"""empty message

Revision ID: 80893e7f7c48
Revises: 210d9d5c6f0e
Create Date: 2022-06-07 08:47:35.761541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80893e7f7c48'
down_revision = '210d9d5c6f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guestbook',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('nama', sa.String(length=80), nullable=False),
    sa.Column('instansi', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=150), nullable=False),
    sa.Column('telepon', sa.String(length=20), nullable=False),
    sa.Column('tujuan', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guestbook')
    # ### end Alembic commands ###
