"""empty message

Revision ID: ba07693d1b4d
Revises: f9a9b13512e9
Create Date: 2022-06-02 22:11:09.360913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba07693d1b4d'
down_revision = 'f9a9b13512e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit_domestik',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debit_proses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('filter_bekas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('masuk', sa.Float(), nullable=True),
    sa.Column('keluar', sa.Float(), nullable=True),
    sa.Column('manifest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('majun_bekas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('masuk', sa.Float(), nullable=True),
    sa.Column('keluar', sa.Float(), nullable=True),
    sa.Column('manifest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oli_bekas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('masuk', sa.Float(), nullable=True),
    sa.Column('keluar', sa.Float(), nullable=True),
    sa.Column('manifest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ph_domestik',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ph_proses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sludge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('masuk', sa.Float(), nullable=True),
    sa.Column('keluar', sa.Float(), nullable=True),
    sa.Column('manifest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sludge')
    op.drop_table('ph_proses')
    op.drop_table('ph_domestik')
    op.drop_table('oli_bekas')
    op.drop_table('majun_bekas')
    op.drop_table('filter_bekas')
    op.drop_table('debit_proses')
    op.drop_table('debit_domestik')
    # ### end Alembic commands ###
