"""empty message

Revision ID: bb38bc8648dd
Revises: cfc07783787b
Create Date: 2022-06-11 07:55:21.752192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb38bc8648dd'
down_revision = 'cfc07783787b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guestbook', sa.Column('foto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guestbook', 'foto')
    # ### end Alembic commands ###
