"""empty message

Revision ID: cc0bee488bfb
Revises: 02bf72a286cc
Create Date: 2022-06-06 06:55:22.078553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0bee488bfb'
down_revision = '02bf72a286cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit_domestik',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('bulan', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debit_proses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('bulan', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ph_domestik',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('bulan', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ph_proses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('bulan', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ph_proses')
    op.drop_table('ph_domestik')
    op.drop_table('debit_proses')
    op.drop_table('debit_domestik')
    # ### end Alembic commands ###
