"""empty message

Revision ID: cfc07783787b
Revises: 4eacaa25be00
Create Date: 2022-06-07 20:42:12.770181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfc07783787b'
down_revision = '4eacaa25be00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filter_bekas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('masuk', sa.Float(), nullable=True),
    sa.Column('keluar', sa.Float(), nullable=True),
    sa.Column('manifest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('majun_bekas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('masuk', sa.Float(), nullable=True),
    sa.Column('keluar', sa.Float(), nullable=True),
    sa.Column('manifest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oli_bekas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('masuk', sa.Float(), nullable=True),
    sa.Column('keluar', sa.Float(), nullable=True),
    sa.Column('manifest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sludge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('masuk', sa.Float(), nullable=True),
    sa.Column('keluar', sa.Float(), nullable=True),
    sa.Column('manifest', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sludge')
    op.drop_table('oli_bekas')
    op.drop_table('majun_bekas')
    op.drop_table('filter_bekas')
    # ### end Alembic commands ###
