"""empty message

Revision ID: df7e10a2b3ba
Revises: ba07693d1b4d
Create Date: 2022-06-05 00:31:54.639499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7e10a2b3ba'
down_revision = 'ba07693d1b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debit_domestik', sa.Column('bulan', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debit_domestik', 'bulan')
    # ### end Alembic commands ###
