"""empty message

Revision ID: f9a9b13512e9
Revises: d0d07ceefae3
Create Date: 2022-05-31 10:19:04.287641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a9b13512e9'
down_revision = 'd0d07ceefae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PH',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debit')
    op.drop_table('PH')
    # ### end Alembic commands ###
